### ISSUE TITLE
Game stalls on getting best zone

### ISSUE THREAD

**Issue by ensingm2** [ensingm2/saliengame_idler#59]
Occasionally, idler seems to stall on "Getting best zone". Seems to be when it finds that the zone it's on is already best, and then doesn't restart a round.

Happening with auto_switch_planet.active=true, Looks like when zone response fails out until max_retries.

Looking into this.

**Comment by ensingm2** [comment]
When zones fail out, and auto_switch_planet.active=true, checkSwitchBetterPlanet() is called with no param, so difficulty_call defaults to false, and the best zone is not started if it is the same as previous. Thinking it's an issue @ line 647, in CheckSwitchBetterPlanet, but unsure.

@Harest, could you take a look at this sometime in the next day or so? You're more familiar with this function than I am.

EDIT: I'm thinking it might be possible to pass in auto_switch_planet.active _as_ the difficulty param in the checkSwitchBetterPlanet() calls as a fix. Unsure though.

**Comment by Harest** [comment]
It should put another message than just "Getting best zone". I also had this issue, that's when you moved the start_round call outside of this because you didn't want to flood the server too much and get in a potential infinite loop as this case shouldn't happen. But with network errors, everything can happen atm :x (though i didn't get any CORS error lastly :crossed_fingers: ; they may have fixed it).  
I've personnaly commented the `if (planet_call === true)` line in the `SwitchNextZone(...)` function. We could remove this entirely if you want and put this back to where it was at first.
