### ISSUE TITLE
Reduce boss dps

### ISSUE THREAD

**Issue by DonSleza4e** [ensingm2/saliengame_idler#85]
Boss dies very fast, could you please reduce bot dps?

Developer of alternative (php) bot reduced dps to 1. As result overall dps of all players decreased, but still boss dies quite fast. Experience is not based on amount of damage done

I received 682k for last boss with reduced damage (overall dps ~200K).  Few hours ago with full dps I received ~500k (overall dps ~300K+)

#86

**Comment by Harest** [comment]
I didn't want to set it to 1 at first because there's players without script too. And a boss with 500M hp appeared. Let me tell you a boss with this amount of hp without a script is a real pain.  
I know XP is based on time you were in the boss fight alive, but i'll not push a modification on boss damages to this low. We can eventually lower them a bit more because boss max hp are quite low now. Maybe even do it more intelligently, by basing the range of damages on the max hp of the boss,

**Comment by Harest** [comment]
This change should be good overall. I also wanted to mention you can't see any XP difference based only on a change you did in your script. The boss HP is shared along all instances.
